---
# 🎉 Cosy UI 预发布工作流
#
# 这个工作流程用于自动化 Cosy UI 组件库的预发布过程。
#
# 工作流程说明：
# 1. 开发流程 (dev 分支)：
#    - 在 dev 分支进行日常开发
#    - 提交并推送到 dev 分支
#
# 2. 预发布流程 (pre 分支)：
#    - 将 dev 分支合并到 pre 分支
#    - 自动升级小版本号
#    - 构建项目
#    - 创建新标签
#    - 发布预发布版本
#
# 发布条件：
# - 推送到 pre 分支时自动触发
# - 发布为预发布版本（prerelease）
#
# 使用方法：
# 1. 日常开发完成后：
#    ```bash
#    git add .
#    git commit -m "feat: your changes"
#    git push origin dev
#    ```
#
# 2. 预发布版本：
#    ```bash
#    git checkout pre
#    git merge dev
#    git push origin pre
#    ```
#
name: 🎉 Prerelease Cosy UI

on:
  push:
    branches: 
      - pre     # 预发布分支
    tags:
      - '*'

# 添加工作流级别的权限
permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write
  statuses: write
  checks: write
  id-token: write

env:
  tag: ${{ github.event.head_commit.id }}
  version: ${{ github.ref_name }}

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.9
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          
      - name: Install Dependencies
        run: pnpm install
        
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Bump Patch Version
        run: |
          cd packages/cosy-ui
          current_version=$(node -p "require('./package.json').version")
          IFS='.' read -r major minor patch <<< "$current_version"
          
          # 版本升级规则说明:
          # 1. 版本格式遵循 semver 规范: major.minor.patch
          # 2. 在预发布流程中，我们只升级 patch 版本号（补丁版本号）
          
          # 如果版本包含预发布标识，则去除它
          if [[ "$patch" == *"-"* ]]; then
            IFS='-' read -r patch_num prerelease <<< "$patch"
            patch=$patch_num
          fi
          
          new_patch=$((patch + 1))
          new_version="${major}.${minor}.${new_patch}"
          
          # 更新 package.json 中的版本号
          npm version $new_version --no-git-tag-version
          echo "VERSION=${new_version}" >> $GITHUB_ENV
          
      - name: Build Packages
        run: pnpm build
        
      - name: Commit Version Changes
        run: |
          git add .
          git commit -m "chore: bump version to ${{ env.VERSION }}"
          git tag v${{ env.VERSION }}
          git push origin pre
          git push origin v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          generate_release_notes: true
          prerelease: true
          
      - name: Sync Version Changes to Dev Branch
        run: |
          # 切换到 dev 分支
          git checkout dev
          
          # 拉取最新的 dev 分支代码
          git pull origin dev
          
          # 将 pre 分支上的版本更新合并到 dev 分支
          # 使用 cherry-pick 只合并版本更新的提交
          git cherry-pick -n $(git log -1 --pretty=format:"%H" pre)
          
          # 提交更改并推送到 dev 分支
          git add .
          git commit -m "chore: sync version ${{ env.VERSION }} from pre branch"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }} 